import uuid

from django.conf import settings
from django.db import models

from common.models import BaseModel, SoftDeleteModel
from organizations.models import Department, Designation


class Employee(SoftDeleteModel):
    """The HR record for a person. User is their login; this is their job."""

    class EmploymentType(models.TextChoices):
        FULL_TIME = "FULL_TIME", "Full Time"
        PART_TIME = "PART_TIME", "Part Time"
        CONTRACT = "CONTRACT", "Contract"
        INTERN = "INTERN", "Intern"

    class Status(models.TextChoices):
        ACTIVE = "ACTIVE", "Active"
        ON_NOTICE = "ON_NOTICE", "On Notice"
        EXITED = "EXITED", "Exited"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="employee",
    )

    # Generated by employees.services.generate_employee_id(), or supplied
    # directly when importing from another HR system. Set once, never
    # changed — payslips and audit records refer to it.
    employee_id = models.CharField(max_length=20, unique=True, blank=True)

    department = models.ForeignKey(
        Department, on_delete=models.PROTECT, related_name="employees"
    )
    designation = models.ForeignKey(
        Designation, on_delete=models.PROTECT, related_name="employees"
    )
    manager = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="team_members",
    )

    date_of_birth = models.DateField(null=True, blank=True)
    date_of_joining = models.DateField()
    date_of_exit = models.DateField(null=True, blank=True)

    employment_type = models.CharField(
        max_length=20,
        choices=EmploymentType.choices,
        default=EmploymentType.FULL_TIME,
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.ACTIVE,
        db_index=True,
    )

    class Meta:
        ordering = ["employee_id"]

    def __str__(self):
        return f"{self.employee_id} - {self.user.get_full_name() or self.user.email}"


class EmployeeDocument(BaseModel):
    """Passports, visas, contracts. Expiry drives the compliance alerts."""

    class DocumentType(models.TextChoices):
        PASSPORT = "PASSPORT", "Passport"
        VISA = "VISA", "Visa"
        EMIRATES_ID = "EMIRATES_ID", "Emirates ID"
        CONTRACT = "CONTRACT", "Contract"
        CERTIFICATE = "CERTIFICATE", "Certificate"
        OTHER = "OTHER", "Other"

    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="documents"
    )
    document_type = models.CharField(max_length=20, choices=DocumentType.choices)
    document_number = models.CharField(max_length=50, blank=True)
    file = models.FileField(upload_to="employee_documents/%Y/%m/")
    issue_date = models.DateField(null=True, blank=True)
    expiry_date = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ["expiry_date"]
        indexes = [models.Index(fields=["document_type", "expiry_date"])]

    def __str__(self):
        return f"{self.get_document_type_display()} - {self.employee.employee_id}"
