# Generated by Django 6.0.8 on 2026-08-27 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, max_length=255)),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('allowed', models.BooleanField(db_index=True, default=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('result_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tool_calls', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='ai.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool_name', '-created_at'], name='ai_aitoolca_tool_na_e12104_idx'), models.Index(fields=['actor', '-created_at'], name='ai_aitoolca_actor_i_222083_idx')],
            },
        ),
    ]
