# Generated by Django 6.0.8 on 2026-08-27 13:45

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.contrib.postgres.operations import CreateExtension

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aitoolcall'),
        ('employees', '0002_alter_employee_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pgvector ships a VectorExtension wrapper, but 0.4.1 forgets to call
        # super().__init__() and so never sets self.hints, which Django 6.0
        # reads. Django's own operation does exactly the same thing:
        # CREATE EXTENSION IF NOT EXISTS vector.
        CreateExtension("vector"),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='knowledge/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Leave empty for a company-wide document.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='employees.employee')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['employee'], name='ai_document_employe_d5ab00_idx')],
            },
        ),
    ]
